### ISSUE TITLE
Alliance players get horde PVP titles.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#334] opened 2019-10-30 16:44 UTC
A guildie of mine just got Grunt and Scout instead of Private and Corporal.

**Comment by Progressive335** [comment] 2019-11-19 16:59
this is probably due being inside bg and playing the opposite faction?

**Comment by Progressive335** [comment] 2019-11-19 17:04
duplicate of https://github.com/Progressive335/Progressive335/issues/280

**Closed by Progressive335** 2019-11-19 17:04 UTC
Labels: bug, medium priority
