### ISSUE TITLE
[Outland] Fishing Schools

### ISSUE THREAD

**Issue by Progressive335** [Progressive335/Progressive335#1005] opened 2020-07-15 05:20 UTC
by Pew

"I've noticed there are no fishing schools in Terrokar forest & Zangramarsh, except for "Steam Pump Flotsam". 
There are schools in nagrand. I haven't checked any other area's yet."

**Comment by VortexPrecision** [comment] 2021-03-24 13:42
Duplicate of
https://github.com/Progressive335/Progressive335/issues/862

**Closed by VortexPrecision** 2021-03-24 13:42 UTC
