### ISSUE TITLE
Stuck in combat after killing mobs on top of the ships in Stranglethorn Vale.

### ISSUE THREAD

**Issue by ImAshes** [Progressive335/Progressive335#342] opened 2019-11-02 06:24 UTC
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**quest=608**

__Place an X between the brackets to specify the ID__

[608] Quest
[1562, 4505] NPC
[608] Quest

**Description of the bug: When you kill mobs on the boats tied to the specified quest, you get stuck in combat forever, even if you hearth or logout.**

**Current behaviour: You kill a mob on the boat, you get stuck in combat.**

**Steps to reproduce the problem: Kill mobs on the top of the boats.**

**How it should work: You shouldn't get stuck in combat.**

**Any other documentation that could be helpful: it might be due to the different levels of the boat and having mobs that aggro you from inside the boat and get stuck in the walls.**

**Comment by Progressive335** [comment] 2020-08-18 16:33
can't reproduce. maybe fixed by latest changed. closing...

**Closed by Progressive335** 2020-08-18 16:33 UTC
Labels: creatures, low priority
