### ISSUE TITLE
Nether Protection(Warlock Talent) does not work as intended

### ISSUE THREAD

**Issue by stucksrazor** [Progressive335/Progressive335#294] opened 2019-10-25 09:20 UTC
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest

**Description of the bug:**
Nether Protection does not proc on a vast area of spells
**Current behaviour:**
Nether Protection only procs on a few spells
**Steps to reproduce the problem:**
duel as a warlock against different classes with spells, many spells wont proc it at all(holy spells, aoe spells, dots)
**How it should work:**
It should proc on every non physical attacks other than hunter stings, rogue poison, deathknights frost and plague strike and Paladins Divine Storm(but it should be able to proc by exorcism)
**Any other documentation that could be helpful:**

**Comment by silverech0** [comment] 2019-11-01 18:55
Some documentation about this please.

**Comment by Progressive335** [comment] 2019-12-31 21:35
closing this since i was unable to reproduce the issue.

**Closed** 2019-12-31 21:35 UTC
Labels: Missing valid information
